export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";